//
//  HomeInteractor.swift
//
//  Created by mohamed hashem on 19/02/2021.
//  Copyright (c) 2021 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift

protocol HomeInteractorInput: class {
    func loadForecastOrcas(cityName: String, resultType: String, unitsType: String, numberOfDays: Int)
}

protocol HomeInteractorOutput: class {
    func present(section: ForecastOrcas)
    func present(error: Error, cityName: String)
}

class HomeInteractor: HomeInteractorInput {

    var output: HomeInteractorOutput?
    let worker = HomeWorker()
    private let disposed = DisposeBag()

    func loadForecastOrcas(cityName: String, resultType: String, unitsType: String, numberOfDays: Int) {
        ForecastOrcasEndPoints.shared
            .provider.rx
            .request(.openWeatherMapByName(cityName: cityName))
            .filterSuccessfulStatusCodes()
            .timeout(.seconds(30), scheduler: MainScheduler.instance)
            .retry(2)
            .map(ForecastOrcas.self)
            .observeOn(MainScheduler.instance)
            .subscribe(onSuccess: { response in
                self.output?.present(section: response)

            }) { error in
                self.output?.present(error: error, cityName: cityName)

            }.disposed(by: disposed)
    }
}
