//
//  HomePresenter.swift
//
//  Created by mohamed hashem on 19/02/2021.
//  Copyright (c) 2021 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresenterInput: class {
    func present(section: ForecastOrcas)
    func present(error: Error, cachedSection: WeatherModel)
    func present(error: Error)
}

protocol HomePresenterOutput: class {
    func display(section: WeatherModel)
    func display(error: Error, cachedSection: WeatherModel)
    func display(error: Error)
}

class HomePresenter: HomePresenterInput {

    weak var output: HomePresenterOutput?
    var weatherSection: [WeatherModel.Sections] = []
    
    func present(section: ForecastOrcas) {
        section.list.forEach { forecastOrcas in
            // create custom model from api model to use it in app
            weatherSection.append(WeatherModel.Sections(cityName: section.city?.name,
                                                 HeaderTitle: forecastOrcas.dt_txt,
                                                 windSpeed: String(forecastOrcas.wind?.speed ?? 0.0),
                                                 windDeg: String(forecastOrcas.wind?.deg ?? 0.0),
                                                 temp: String(forecastOrcas.main?.temp ?? 0.0),
                                                 pressure: String(forecastOrcas.main?.pressure ?? 0),
                                                 description: forecastOrcas.weather?.first?.description))
        }
        let weather = WeatherModel(sections: weatherSection)

        output?.display(section: weather)
    }
    
    func present(error: Error, cachedSection: WeatherModel) {
        output?.display(error: error, cachedSection: cachedSection)
    }

    func present(error: Error) {
        output?.display(error: error)
    }
}
