//
//  HomeRouter.swift
//
//  Created by mohamed hashem on 19/02/2021.
//  Copyright (c) 2021 mohamed hashem. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum HomeDirection {
    case errorPopUp
}

class HomeRouter {
    
  weak var viewController: HomeViewController!

  // MARK: Routing
    func routeToSomewhere(segue: UIStoryboardSegue?) {
        if segue?.identifier == "ErrorPopUp" {
            let errorViewController = segue?.destination as? ErrorPopUpViewController
            errorViewController?.errorMessageIs = viewController.errorMessageIs
            errorViewController?.reLoadForecastOrcas = {
                self.viewController.reLoadForecastOrcas()
            }
        }
    }

  // MARK: Navigation
    func navigateBySegue(to: HomeDirection) {
        switch to {
        case .errorPopUp:
            viewController.performSegue(withIdentifier: "ErrorPopUp", sender: nil)

        }
    }
}
